### ISSUE TITLE
Error collecting xmltv since yesterday

### ISSUE THREAD

**Issue by megahorst** [kibuan/xmltv_docker#1]
First at all, I like this xmltv solution for Synology docker very much. Thx for your effort for the xmltv community.
It has worked for a long time without any issue. But since yesterday I receive the following errror and no xmltv was downloaded:
(have masked my tv_grab_eu_epgdata pin with <xxx>)

Grabber configuration file is: /root/.xmltv/tv_grab_eu_epgdata.conf
Running: tv_grab_eu_epgdata --config-file /root/.xmltv/tv_grab_eu_epgdata.conf --output /opt/xml/xmltv.xml --days 14
Downloading include zip file http://www.epgdata.com/index.php?action=sendInclude&iOEM=&pin=<xxx>&dataType=xml
IO error: opening /tmp/9CzlWZp00i//include.zip for read : No such file or directory
 at /usr/share/perl5/vendor_perl/Archive/Zip/Archive.pm line 561.
        Archive::Zip::Archive::read(Archive::Zip::Archive=HASH(0x557255337160), "/tmp/9CzlWZp00i//include.zip") called at /usr/share/perl5/vendor_perl/Archive/Zip/Archive.pm line 55
        Archive::Zip::Archive::new("Archive::Zip::Archive", "/tmp/9CzlWZp00i//include.zip") called at /usr/share/perl5/vendor_perl/Archive/Zip.pm line 316
        Archive::Zip::new("Archive::Zip", "/tmp/9CzlWZp00i//include.zip") called at /usr/bin/tv_grab_eu_epgdata line 367        main::unzip("/tmp/9CzlWZp00i//include.zip") called at /usr/bin/tv_grab_eu_epgdata line 359
        main::prepareinclude(HASH(0x557254fd07c8), HASH(0x557254fcfcd0)) called at /usr/bin/tv_grab_eu_epgdata line 298
Can't call method "memberNames" on an undefined value at /usr/bin/tv_grab_eu_epgdata line 368.
grabber finished, exiting...

Do you have any idea how to overcome this?

Thx and BR

**Comment by kibuan** [comment]
Hi megahorst, 
It's great to here that you have been using my solution! 
The error seems to be related to the grapper or epg-source you use. I'm not involved in the main xmltv project, so I can't help you fix this error. My only contribution is the instructions in this repository helping people creating their own xmltv docker image based on the main project for easy execution of the xmltv code in a docker environment.
If you have been using the same container for a long time, I would suggest that you try and rebuild your docker image. When you do that it will reinstall xmltv from the main source. You will then get the latest version of the xmltv project in your new docker image. If this does not solve the issue, try asking for help in the xmltv community or report the issue in the xmltv repository.
