### ISSUE TITLE
Centos deprecation

### ISSUE THREAD

**Issue by obushnell** [kibuan/xmltv_docker#2]
Over the weekend I was forced to rebuild my xmltv docker image based on your Dockerfile. Centos has been deprecated and has been removed as of June, 2024. This means your Dockerfile can no longer be built. Please switch to another distro. The xmltv repo has many to choose from.

**Comment by obushnell** [comment]
I have filed a bug with xmltv, [Bug 236](https://github.com/XMLTV/xmltv/issues/236), to have them remove the invalid docker files.

**Comment by kibuan** [comment]
Thanks for your contribution. I will review it and update when I'm home from vacation in a few days.
